dbt_project:
  target: dev
  outputs:
    dev:
      type: bigquery
      method: service-account
      project: neneco
      dataset: "{{ env_var('DBT_DBNAME', 'dbt_bd') }}"
      threads: 4 # Must be a value of 1 or greater
      keyfile: /home/rsantos/dbt/neneco-015e4604ab85.json
